INSERT INTO questions (quiz_id, question) VALUES (1, 'What is the formula for the area of rectangle?');
INSERT INTO questions (quiz_id, question) VALUES (1, 'What is half of 84?');
INSERT INTO questions (quiz_id, question) VALUES (1, 'What is the formula for the area of triangle?');
INSERT INTO questions (quiz_id, question) VALUES (1, 'How do you find the surface area of a cylinder?');
INSERT INTO questions (quiz_id, question) VALUES (1, 'What is the result for 6 * 4 =  ?');
INSERT INTO questions (quiz_id, question) VALUES (1, 'What is the next EVEN number after 38?');
INSERT INTO questions (quiz_id, question) VALUES (2, 'Marlin and Nemo are what type of fish?');
INSERT INTO questions (quiz_id, question) VALUES (2, 'Which part of a plant is similar to a human spine because it provides support for the plant?');
INSERT INTO questions (quiz_id, question) VALUES (2, 'Which link in the food chain describes the tranfer of energy from producer?');
INSERT INTO questions (quiz_id, question) VALUES (2, 'In which part of a plant does photosynthesis take place?');
INSERT INTO questions (quiz_id, question) VALUES (2, 'What process of plant growth describes when roots first begin to grow in the soil?');
INSERT INTO questions (quiz_id, question) VALUES (2, 'Which organ in the human body is responsible for regulating body temperature?');
INSERT INTO questions (quiz_id, question) VALUES (3, 'Who first discovered Canada?');
INSERT INTO questions (quiz_id, question) VALUES (3, 'Who owns Canada?');
INSERT INTO questions (quiz_id, question) VALUES (3, 'Whose portrait is on the $5 bill?');
INSERT INTO questions (quiz_id, question) VALUES (3, 'What is the name of the first Prime Minister of Canada?');
INSERT INTO questions (quiz_id, question) VALUES (3, 'Whose portrait is on the $10 bill?');
INSERT INTO questions (quiz_id, question) VALUES (3, 'In what year was Canada founded?');
INSERT INTO questions (quiz_id, question) VALUES (4, 'What is the capital of California?');
INSERT INTO questions (quiz_id, question) VALUES (4, 'What is the capital of Canada?');
INSERT INTO questions (quiz_id, question) VALUES (4, 'What is the capital of Texas?');
INSERT INTO questions (quiz_id, question) VALUES (4, 'What is the capital of India?');
INSERT INTO questions (quiz_id, question) VALUES (4, 'What is the capital of USA?');
INSERT INTO questions (quiz_id, question) VALUES (4, 'What is the capital of Turkey?');
INSERT INTO questions (quiz_id, question) VALUES (5, 'LOL. Laughing out...');
INSERT INTO questions (quiz_id, question) VALUES (5, 'IMO. In my...');
INSERT INTO questions (quiz_id, question) VALUES (5, 'PPL. There were too many...');
INSERT INTO questions (quiz_id, question) VALUES (5, 'AMA. Ask me...');
INSERT INTO questions (quiz_id, question) VALUES (5, 'IKR. I know...');
INSERT INTO questions (quiz_id, question) VALUES (5, 'OMG. Oh my...');
INSERT INTO questions (quiz_id, question) VALUES (6, 'We have to go home soon so we can hit the hay!');
INSERT INTO questions (quiz_id, question) VALUES (6, 'Just tell me. I am all ears!');
INSERT INTO questions (quiz_id, question) VALUES (6, 'I will believe it when pigs fly!');
INSERT INTO questions (quiz_id, question) VALUES (6, 'Mr. and Mrs. Smith tied the knot in May.');
INSERT INTO questions (quiz_id, question) VALUES (6, 'Do not be ad couch potato, get outside and play!');
INSERT INTO questions (quiz_id, question) VALUES (6, 'This test is a piece of cake.');
INSERT INTO questions (quiz_id, question) VALUES (7, 'The official who controls the game in some sports, e.g. football is called...');
INSERT INTO questions (quiz_id, question) VALUES (7, 'When a game is finished without either team winning, e.g. 1-1, the game ends in a...');
INSERT INTO questions (quiz_id, question) VALUES (7, 'The long metal stick used for hitting the ball in golf is...');
INSERT INTO questions (quiz_id, question) VALUES (7, 'Who trains a person or team in sport?');
INSERT INTO questions (quiz_id, question) VALUES (7, 'The leader of a sports team is the...');
INSERT INTO questions (quiz_id, question) VALUES (7, 'The sticks used to push youself forward while skiing are...');
INSERT INTO questions (quiz_id, question) VALUES (8, 'Where was mario first appeared?');
INSERT INTO questions (quiz_id, question) VALUES (8, 'What was marios name in donkey kong?');
INSERT INTO questions (quiz_id, question) VALUES (8, 'When was luigi first introduced?');
INSERT INTO questions (quiz_id, question) VALUES (8, 'Who created Mario?');
INSERT INTO questions (quiz_id, question) VALUES (8, 'When was the NES first introduced?');
INSERT INTO questions (quiz_id, question) VALUES (8, 'What do arcade machines eat?');
INSERT INTO questions (quiz_id, question) VALUES (9, 'The lines in the treble staff from bottom to top are...');
INSERT INTO questions (quiz_id, question) VALUES (9, 'Which of these woodwind instruments sounds the highest?');
INSERT INTO questions (quiz_id, question) VALUES (9, 'The spaces of the bass clef from bottom to top are...');
INSERT INTO questions (quiz_id, question) VALUES (9, 'Which of these string instruments sounds the lowest?');
INSERT INTO questions (quiz_id, question) VALUES (9, 'What is the term for playing music the first time you see it?');
INSERT INTO questions (quiz_id, question) VALUES (9, 'Which key signature has one sharp?');


